export const SkillsSet = [
  {
    key: "1",
    name: "HTML",
    url: "/images/html.png",
    width: 64,
    height: 64,
  },
  { key: "2", name: "CSS", url: "/images/css-3.png", width: 64, height: 64 },
  {
    key: "3",
    name: "JavaScript",
    url: "/images/js.png",
    width: 64,
    height: 64,
  },
  {
    key: "4",
    name: "TypeScript",
    url: "/images/typescript.png",
    width: 64,
    height: 64,
  },
  {
    key: "5",
    name: "React",
    url: "/images/react.png",
    width: 64,
    height: 64,
  },
  {
    key: "6",
    name: "Tailwind",
    url: "/images/Tailwind.png",
    width: 64,
    height: 64,
  },
  {
    key: "7",
    name: "NextJS",
    url: "/images/nextjs.png",
    width: 64,
    height: 64,
  },
  {
    key: "8",
    name: "NodeJS",
    url: "/images/nodejs.png",
    width: 64,
    height: 64,
  },
  { key: "9", name: "PHP", url: "/images/php.png", width: 64, height: 64 },
  {
    key: "10",
    name: "GraphQL",
    url: "/images/GraphQL.png",
    width: 64,
    height: 64,
  },
];
